### PR TITLE
Feature error handling

### PR DESCRIPTION
**Pull request by pierr**
- fix ws call on delete case (single and group actions)
- Add error handling on fetch, delete and delete group actions
- Add smart component in the index instead of the example.
  image

### CODE REVIEW

**Comment by pierr** [comment]
Some tests are missing on the new error reducer. Will be added tomorrow morning...

**Comment by pierr** [comment]
Maybe in a separate pull request

**Comment by pierr** [comment]
@Bernardstanislas  you can do this now instead of kissing your hand...
image

**Comment by Bernardstanislas** [comment]
Holy s***\* (going to hell for this one)

**Pull request merged**
